services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lookatthatmongo
    env_file:
      - .env
    environment:
      # --- Application Configuration ---
      # Adjust these based on your config package needs
      LOG_LEVEL: "debug" # Example: Set log level
      OPENAI_API_KEY: ${OPENAI_API_KEY} # IMPORTANT: Replace or use secrets
      POLLING_INTERVAL: "60s" # Example: Polling interval
      HISTORY_FILE: "/data/optimization_history.json" # Example: Storage path inside container
      IMPROVEMENT_THRESHOLD: "5.0" # Example: Percentage threshold

      # --- MongoDB Connection ---
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      # MONGO_COLLECTION_NAME: "testcollection" # Optional: If monitoring a specific collection
    volumes:
      # Optional: Mount a volume for persistent storage if needed (e.g., history file)
      - app_data:/data
    restart: unless-stopped

  # mongo:
  #   image: mongo:latest
  #   container_name: lookatthatmongo_mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "admin"
  #     MONGO_INITDB_ROOT_PASSWORD: "password"
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - app_network
  #   restart: unless-stopped

volumes:
  app_data:
  mongo_data:

networks:
  app_network:
    driver: bridge
